# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunLife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FunLife
  pod 'FirebaseCore', '9.0'
  pod 'FirebaseAuth', '9.0'
  pod 'FirebaseFirestore', '9.0'
  pod 'FirebaseStorage', '9.0'
  pod 'FirebaseDatabase', '9.0'
  pod 'FirebaseFirestoreSwift', '9.0'
  pod 'Firebase/Crashlytics' 
  pod 'Firebase/Analytics'
  pod 'FSCalendar'
  pod 'IQKeyboardManager'
end
