# Uncomment the next line to define a global platform for your project
# platform :ios, '15.0'

target 'FunLife' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FunLife
  pod 'FirebaseCore', '9.0'
  pod 'FirebaseAuth', '9.0'
  pod 'FirebaseFirestore', '9.0'
  pod 'FirebaseStorage', '9.0'
  pod 'FirebaseDatabase', '9.0'
  pod 'FirebaseFirestoreSwift', '9.0'
  pod 'Firebase/Crashlytics' 
  pod 'Firebase/Analytics'
  pod 'FSCalendar'
  pod 'IQKeyboardManager'
  pod 'Kingfisher'
  pod 'lottie-ios'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    # DT_TOOLCHAIN_DIR 換成 TOOLCHAIN_DIR
    target.build_configurations.each do |config|
      xcconfig_path = config.base_configuration_reference.real_path
      xcconfig = File.read(xcconfig_path)
      xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
      File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
    end

    # BoringSSL-GRPC 處理
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end